name: snakemake_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake=8.14.0
  - pulp=2.7.0
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - networkx
  # Add other dependencies as needed
