include ../../ParlayANN/algorithms/bench/parallelDefsANN

model_inflate : model_inflate.cpp
	$(CC) $(CFLAGS) -o model_inflate model_inflate.cpp $(LFLAGS) 

heat_vecs : heat_vecs.cpp
	$(CC) $(CFLAGS) -o heat_vecs heat_vecs.cpp $(LFLAGS) 