include ../../ParlayANN/algorithms/bench/parallelDefsANN

compute_clustering_coeffs : compute_clustering_coeffs.cpp
	$(CC) $(CFLAGS) -I../../ParlayANN/parlaylib/include -o compute_clustering_coeffs compute_clustering_coeffs.cpp $(LFLAGS) 
